name: build
on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
  schedule:
    - cron: '34 17 * * 4'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET_IMAGE: ghcr.io/sarisia/vscode-dev-containers-multiarch/base:ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: sarisia
          password: ${{ github.token }}
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      # - uses: docker/setup-buildx-action@v1
      - run: |
          cd vscode-dev-containers/containers/ubuntu/.devcontainer
          docker buildx build --platform linux/arm64 -t ${{ env.TARGET_IMAGE }} --push --build-arg VARIANT=focal --file base.Dockerfile .
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: ghcr.io/sarisia/vscode-dev-containers-multiarch:ubuntu (arm64)
