name: build
on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET_IMAGE: ghcr.io/sarisia/vscode-dev-containers-multiarch/base:ubuntu
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: sarisia
          password: ${{ github.token }}
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      # - uses: docker/setup-buildx-action@v1
      - run: docker buildx build --platform linux/arm64 -t ${{ env.TARGET_IMAGE }} --push --file base.Dockerfile vscode-dev-containers/containers/ubuntu/.devcontainer
      - uses: sarisia/actions-status-discord@v1
